### ISSUE TITLE
Tenant selection panel showed in generated report

### ISSUE THREAD

**Issue by alexz00** [opendistro-for-elasticsearch/kibana-reports#311]
Hi,
I'm using ODFE 1.12 with the following configuration:
- ODFE security enabled
- Kibana SSL disabled
- Kibana port 5601 (default)
- Kibana multi-tenancy enabled

When I try to generate a report, the tenant selection panel is displayed in the report:
![On_demand_report_2021-02-04T18_45_11 039Z_1c3ac8f0-6719-11eb-b5d4-3f3ab99c27bb](https://user-images.githubusercontent.com/26408524/106944487-ebf43380-6726-11eb-871a-ddfc014a4f7c.png)

**Comment by anirudha** [comment]
this is weird :( , investigating, will fix asap

**Comment by zhongnansu** [comment]
If you select "remember my selection", will it still be there in the reports?

**Comment by alexz00** [comment]
Yes, I tried also after having selected 'remember my selection', the issue still happens.

**Comment by zhongnansu** [comment]
> Yes, I tried also after having selected 'remember my selection', the issue still happens.

Thanks for the feedback, this is indeed an issue, we'll look into this.

**Comment by zhongnansu** [comment]
Since reporting launch a chromium instance to access the url for visual report generation. I believe the tenant preference is saved only in the browser cache. 

Meanwhile, I found some related open issues in security-kibana-plugin repo. If the tenant preference is preserved in the url, the reporting will have no issue.
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/74
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/123

https://discuss.opendistrocommunity.dev/t/missing-security-tenant-parameter-in-dashboard-url-when-sharing-or-embedding-in-latest-version/4013
