### ISSUE TITLE
How to send a report as part of email/slack?

### ISSUE THREAD

**Issue by Coderranker** [opendistro-for-elasticsearch/kibana-reports#377]
Hi,
Thank you all for your amazing work. I am using open-distro and things are working well. My new use-case is to send the generated report every week to our team on slack/email. I see in the description that we support sending email/slack - 

` Scheduled reports can be sent to (shared with) self or various stakeholders within the organization such as, including but not limited to, executives, managers, engineers (developers, DevOps, IT Engineer) in the form of pdf, hyperlinks, csv, excel via various channels such as email, slack, Amazon Chime`

But I'm not able to figure out how to do them. I do not see an option in kibana -> Reporting to perform such action. 
Or If we have an api to download the report, anything.

I will be happy to get a lead on this or if any documentation persist.

Cheers.

**Comment by zhongnansu** [comment]
@Coderranker 
Hi, the readme is confusing. We actually removed this feature due to some technical reason when we released the product. However we know it's an important feature and it still on the roadmap.

Since recently we are migrating OpenDistro to OpenSearch, and any new features will be released only on Opensearch. We are slowly deprecating OpenDistro. Please refer to the issue in Opensearch for tracking. https://github.com/opensearch-project/dashboards-reports/issues/18

Thanks

**Comment by Coderranker** [comment]
Thanks for the info zhongnansu. Do we have a timeline for the changes to be merged?

**Comment by zhongnansu** [comment]
@Coderranker Please refer to the roadmap for tracking, notification will be a new plugin, and reporting will integrate with it 
https://github.com/orgs/opensearch-project/projects/1#column-14092178
