### ISSUE TITLE
CVS report is not getting generated from a saved search when using "Today" form the date picker

### ISSUE THREAD

**Issue by rpotnuru** [opendistro-for-elasticsearch/kibana-reports#384]
CVS report is not getting generated from a saved search when using Today form the date picker as my time filter, however when I use a specific duration like from and to date it is working.

When using today in the time filter I am seeing errors in the JavaScript Console. PFB the error trace.
_Uncaught TypeError: Cannot read property 'diff' of undefined
    at getTimeFieldsFromUrl (opendistroReportsKibana.plugin.js:1)
    at HTMLButtonElement.<anonymous> (opendistroReportsKibana.plugin.js:1)
    at HTMLDocument.dispatch (kbn-ui-shared-deps.js:404)
    at HTMLDocument.m.handle (kbn-ui-shared-deps.js:404)
getTimeFieldsFromUrl @ opendistroReportsKibana.plugin.js:1
(anonymous) @ opendistroReportsKibana.plugin.js:1
dispatch @ kbn-ui-shared-deps.js:404
m.handle @ kbn-ui-shared-deps.js:404_

Attaching screenshot for your reference:
<img width="1677" alt="Screen Shot 2021-07-07 at 1 37 15 PM" src="https://user-images.githubusercontent.com/3529965/124825662-cca54080-df28-11eb-933c-7e733770b892.png">

Kibana Version: v 7.10.2
Thanks, Ravi Ponturu.

**Comment by zhongnansu** [comment]
Hi this is a [known issue](https://github.com/opensearch-project/dashboards-reports/issues/88) and it's on our roadmap to fix. However, since recently we have migrated to Opensearch and are deprecating the open distro for elasticsearch. Any fix and new features will only apply to the new project under Opensearch. Please take a look and leave any comment over there.
