### ISSUE TITLE
Not able to configure email option for report

### ISSUE THREAD

**Issue by mlsb101** [opendistro-for-elasticsearch/kibana-reports#385]
Hi, 

I want to schedule a report to be sent to email address, but i am not able to find any option to configure email for an alert. 
Can you let me know if this feature is there or not in Opendistro Kibana. 

Kibana version : 7.10.2

**Comment by zhongnansu** [comment]
@mlsb101 Hi, the send notifcation fearure is not available in any version of Opendistro Reporting. However the feature is still on our roadmap and the development is in progress. Since we migrated to Opensearch recently, and we are deprecating OpenDistro. So notification feature will only be available in OpenSearch.

https://github.com/opensearch-project/dashboards-reports/issues/72
